[package]
name = "rspotd"
version = "0.1.0"
edition = "2021"
description = "Generate ARRIS/CommScope Password of the Day for modems"
keywords = ["arris", "commscope", "modem", "docsis", "password", "potd"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
regex = "1"